hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1-n5

build_gc: LXR

runtimes:
  jdk-lxr-spinlock:
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 8355c0ad11ec0b86f8f93ddee0abd6597f638cc3
      mmtk-openjdk: 46546ed41d28dd101eb57dca5422b73148f6ee06
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting
    pgo: true
  jdk-lxr-cas:
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: 27d6d16f5016322c9001237e98f0265ad3fba551
      mmtk-openjdk: 46546ed41d28dd101eb57dca5422b73148f6ee06
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting
    pgo: true

configs:
  # LXR
  - jdk-lxr-spinlock|lxr|common3|tph|disable_thp
  - jdk-lxr-cas|lxr|common3|tph|disable_thp
