hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1-n5
  benchmarks.dacapochopin:
    # - lusearch
    # - h2
    # - cassandra
    # - tomcat
    # - spring
    # - tradebeans
    - kafka
    - avrora
    - batik
    - biojava
    - eclipse
    - fop
    - graphchi
    - h2o
    - jme
    - jython
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing
    - tradesoap

build_gc: LXR,Immix

runtimes:
  jdk-mmtk-baseline: &base
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-mmtk-xput-p/jdk-11.0.19
    commits:
      mmtk-core: 352e04e671a08288f3f189443f3339fa98a19172 # wp/dev-baseline
      mmtk-openjdk: a0c83638f8da90ed51791a789d6253e016866b9d # wp/dev-baseline
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting,mmtk/push,mmtk/satb_timer
    pgo: true
  # jdk-mmtk-item-steal:
  #   <<: *base
  #   home: $BUILDS/jdk-lxr-2/jdk-11.0.19
  #   commits:
  #     mmtk-core: 92c72028e1a1cb803b26ed34e72ea0cb8de2d971 # wp/dev-stealing
  #     mmtk-openjdk: a0c83638f8da90ed51791a789d6253e016866b9d # wp/dev-baseline
  #     openjdk: bc9669aaed
  # features: mmtk/no_meta_counting,mmtk/push,mmtk/satb_timer,mmtk/steal_bulk
  jdk-mmtk-dep:
    <<: *base
    home: $BUILDS/jdk-mmtk-xput-d/jdk-11.0.19
    commits:
      mmtk-core: bfea2b0a793f2e9d00cd41e0c8fcc8b9d2bae6f5 # wp/dev-dep
      mmtk-openjdk: 65fa88d8fcd58890bd64c211ff1a21e36a642532 # wp/dev-dep
      openjdk: bc9669aaed
    pgo: true
  jdk-mmtk-all:
    <<: *base
    home: $BUILDS/jdk-mmtk-xput-s/jdk-11.0.19
    commits:
      mmtk-core: 705dae91442f085db3030eb66a57508f4a8a9335 # wp/dev-merge
      mmtk-openjdk: 65fa88d8fcd58890bd64c211ff1a21e36a642532 # wp/dev-dep
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting,mmtk/push,mmtk/satb_timer,mmtk/steal_bulk
    pgo: true

configs:
  - jdk-mmtk-baseline|lxr|common3|tph_perf|disable_thp
  - jdk-mmtk-baseline|ix|common3|tph_perf|disable_thp
  - jdk-mmtk-dep|lxr|common3|tph_perf|disable_thp
  - jdk-mmtk-dep|ix|common3|tph_perf|disable_thp
  - jdk-mmtk-all|ix|common3|tph_perf|disable_thp
  - jdk-mmtk-all|lxr|common3|tph_perf|disable_thp
